# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/MAT281_2022
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/MAT281_2022
repo_url: https://github.com/fralfaro/MAT281_2022
edit_uri: ''



# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro


# TOC
nav:
    - Home: index.md
    - Basic Tools:
        - Introducción: lectures/basic_tools/basic_tools/lecture_000_intro.ipynb
        - Configuraciones: lectures/basic_tools/basic_tools/lecture_000_configuraciones.ipynb
        - Linux: lectures/basic_tools/basic_tools/lecture_011_os.ipynb
        - Git: lectures/basic_tools/basic_tools/lecture_015_git.ipynb
        - IDE: lectures/basic_tools/basic_tools/lecture_013_ide.ipynb
        - Python: lectures/basic_tools/basic_tools/lecture_012_python.ipynb
        - Jupyter Notebook: lectures/basic_tools/basic_tools/lecture_014_jupyter.ipynb
        - Google Colab: lectures/basic_tools/basic_tools/lecture_016_colab.ipynb
    - Scientific Computing:
        - Numpy: lectures/data_manipulation/scientific_computing/numpy.ipynb
        - Scipy: lectures/data_manipulation/scientific_computing/scipy.ipynb
        - Sympy: lectures/data_manipulation/scientific_computing/sympy.ipynb
    - Data manipulation:
        - Introducción: lectures/data_manipulation/data_manipulation/base_datos.ipynb
        - Pandas: lectures/data_manipulation/data_manipulation/pandas.ipynb
        - Groupby: lectures/data_manipulation/data_manipulation/groupby.ipynb
        - Merge & Concat: lectures/data_manipulation/data_manipulation/merge_concat.ipynb
        - Pivot Tables: lectures/data_manipulation/data_manipulation/pivot.ipynb
    - Visualization:
        - Introducción: lectures/data_manipulation/visualization/introduction.ipynb
        - Matplotlib: lectures/data_manipulation/visualization/matplotlib.ipynb
        - Seaborn: lectures/data_manipulation/visualization/seaborn.ipynb
    - Machine Learning:
        - Introducción: lectures/ml/introduccion_ml/introduccion.ipynb
        - Regresión: lectures/ml/analisis_supervisado_regresion/02_regresion_lineal.ipynb
        - Clasificación: lectures/ml/analisis_supervisado_clasificacion/02_clasificacion.ipynb
        - Clustering: lectures/ml/analisis_no_supervisado/03_clustering.ipynb
        - Reducción Dimensionalidad: lectures/ml/analisis_no_supervisado/03_reduccion_dimensionalidad.ipynb
        - Overffiting: lectures/ml/overfitting/04_overfitting_underfitting.ipynb
        - Reducir Overfiting: lectures/ml/overfitting/04_reducir_overfitting.ipynb
        - Series Temporales: lectures/ml/time_series/05_series_temporales.ipynb


# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
